language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
  - rust: nightly
    env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
  exclude:
  - rust: beta
    env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
  - rust: stable
    env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  cd cudnn
  travis-cargo build -- --no-default-feature --features "travis"s &&
  travis-cargo test -- --no-default-features --features "travis"
  travis-cargo doc -- --no-default-features --features "travis"
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
env:
  global:
    secure: hTYDLFNmzEazAYd0eBY0HearyERReUHUSSmwGvdVBIX0Vbltvq1vKmUJAneDwzRiehL9HyrX5HV4OkbA6XNseFXXuTYjC/vbSjyN+TcXDLUWIhTMTsLEdh3h5g/XQN9lv03ovmqPDA2owoggxNosRt/10dclV9GiyYHF3ozbJOur4DIMqCi9ta9FpE9KMHsC6HSSdFgW5vTcrKsk9M2GBWzy52lAUQjm1qw1zHG2FmopbzXruaeFHIV0V2owww2FxLp6Hh592/WTX0gj6AMR1M8DfvALV5vDB+F49EWWHnC64RHGW74muQXrGPmG4nk0oUE4EzjX+XWTaRUCQ9p1nkPxFcWOCqykASOCnXNLfdDH47mqRmpjvHwvS5Ivd0FWaHPWmHbxu9CJ9zJImijHPgRpKVVmxh0BqKMG72QCUkONr4nKCW/vbCOvJgnwXpFXLLhYgqQsjaT/kqGR4VbB6PxKeI0+z8AnKE6RAzZmvN1U3Bx3kZ5xEaJCfytpXGBROTyXV4gvhyyDmdG8MnYuCPlY4Ov8LC7vWAmyp7nbE/IYtGePz6B6ec5bl9qrv9zD14FOT+MFvxqZkYaNUgImTouUG/MvH1lmSrPjqalxdmq8YTiGFgmh8vFZ2ovPbfPRl6usEMcgd8CjNuewb4Dz/XNYEmsS0C3+o3HMCNJ/YVc=
  matrix:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=travis
  - TRAVIS_CARGO_NIGHTLY_FEATURE=lint
