[package]
name            = "collenchyma-nn"
description     = "Collenchyma plugin for full Neural Network algorithm support"
version         = "0.0.1"
authors         = ["Michael Hirn <mj@autumnai.com>",
                   "Maximilian Goisser <max@autumnai.com>"]

repository      = "https://github.com/autumnai/collenchyma-nn"
homepage        = "https://github.com/autumnai/collenchyma-nn"
documentation   = "https://autumnai.github.io/collenchyma-nn"
readme          = "README.md"

keywords        = ["neural-network", "collenchyma", "computation", "hpc", "plugin"]
license         = "MIT"

[dependencies]
# collenchyma = { git = "https://github.com/autumnai/collenchyma.git", rev = "fdd030d", default-features = false }
collenchyma = { path = "/home/hobofan/collenchyma", default-features = false }
# cudnn = { version = "1.0.0", optional = true }
cudnn = { path = "/home/hobofan/rust-cudnn/cudnn", optional = true }
libc = "0.2"
lazy_static = "0.1"

clippy = { version = "0.0.27", optional = true }

[features]
default = ["native", "cuda", "opencl"]
native = ["collenchyma/native"]
cuda = ["collenchyma/cuda", "cudnn"]
opencl = ["collenchyma/opencl"]

travis = ["native"]
dev = []
lint = ["clippy"]
