[package]
name            = "collenchyma-nn"
description     = "Collenchyma plugin for full Neural Network algorithm support"
version         = "0.0.1"
authors         = ["MichaelHirn <michael.hirn@storeness.de>",
                   "Maximilian Goisser <max@autumnai.com>"]

repository      = "https://github.com/autumnai/collenchyma-nn"
homepage        = "https://github.com/autumnai/collenchyma-nn"
documentation   = "https://autumnai.github.io/collenchyma-nn"
readme          = "README.md"

keywords        = ["neural-network", "collenchyma", "computation", "hpc", "plugin"]
license         = "MIT"

[dependencies]
collenchyma = { version = "0.0.5", default-features = false }
lazy_static = "0.1"

cudnn = { version = "0.1", optional = true }

clippy = { version = "0.0.27", optional = true }

[features]
default = ["native", "cuda", "opencl"]
native = ["collenchyma/native"]
cuda = ["collenchyma/cuda", "cudnn"]
opencl = ["collenchyma/opencl"]

travis = ["native"]
dev = []
lint = ["clippy"]
